from kmer_tools.download_genbank.orga_names_sorted import *


Embryophyta_Names_NCBI = [
    "Physcomitrium patens",
    "Brachypodium distachyon",
    "Oryza sativa Japonica Group",
    "Zea mays",
    "Sorghum bicolor",
    "Setaria italica",
    "Ananas comosus",
    "Elaeis guineensis",
    "Musa acuminata subsp. malaccensis",
    "Asparagus officinalis",
    "Papaver somniferum",
    "Vitis vinifera",
    "Arabidopsis thaliana",
    "Brassica napus",
    "Camelina sativa",
    "Gossypium raimondii",
    "Theobroma cacao",
    "Citrus sinensis",
    "Populus trichocarpa",
    "Manihot esculenta",
    "Arachis duranensis",
    "Phaseolus vulgaris",
    "Cajanus cajan",
    "Vigna angularis",
    "Medicago truncatula",
    "Lupinus angustifolius",
    "Fragaria vesca subsp. vesca",
    "Malus domestica",
    "Prunus mume",
    "Cucumis sativus",
    "Beta vulgaris subsp. vulgaris",
    "Nicotiana attenuata",
    "Sesamum indicum",
    "Helianthus annuus",
]

Protista_Names_NCBI = [
    "Dictyostelium discoideum AX4",
    "Leishmania donovani",
    "Leishmania infantum JPCM5",
    "Leishmania major strain Friedlin",
    "Trypanosoma brucei brucei TREU927",
    "Neospora caninum Liverpool",
    "Toxoplasma gondii ME49",
    "Cryptosporidium parvum Iowa II",
    "Plasmodium vivax",
    "Plasmodium falciparum 3D7",
    "Plasmodium berghei ANKA",
    "Plasmodium cynomolgi strain B",
    "Plasmodium coatneyi",
    "Plasmodium gaboni",
    "Theileria annulata",
    "Theileria parva strain Muguga",
    "Theileria orientalis strain Shintoku",
    "Babesia microti strain RI",
    "Babesia bigemina",
    "Paramecium tetraurelia strain d4-2",
    "Phaeodactylum tricornutum CCAP 1055_1",
    "Ectocarpus siliculosus",
    "Thalassiosira pseudonana CCMP1335",
    "Nannochloropsis gaditana",
    "Cyanidioschyzon merolae strain 10D",
    "Chlamydomonas reinhardtii",
    "Micromonas commoda",
    "Bathycoccus prasinos",
    "Ostreococcus lucimarinus CCE9901",
    "Ostreococcus tauri",
]

Fungi_Names_NCBI = [
    "Encephalitozoon cuniculi GB-M1",
    "Encephalitozoon intestinalis ATCC 50506",
    "Ustilago maydis 521",
    "Sporisorium reilianum SRZ2",
    "Cryptococcus gattii WM276",
    "Pyrrhoderma noxium",
    "Schizosaccharomyces pombe",
    "Saccharomyces cerevisiae S288C",
    "Tetrapisispora phaffii CBS 4417",
    "Tetrapisispora blattae CBS 6284",
    "Zygosaccharomyces rouxii",
    "Naumovozyma castellii CBS 4309",
    "Lachancea thermotolerans CBS 6340",
    "Eremothecium gossypii ATCC 10895",
    "[Candida] glabrata",
    "Candida albicans SC5314",
    "Debaryomyces hansenii CBS767",
    "Komagataella phaffii GS115",
    "Yarrowia lipolytica CLIB122",
    "Pichia kudriavzevii",
    "Ogataea parapolymorpha DL-1",
    "Zymoseptoria tritici IPO323",
    "Neurospora crassa OR74A",
    "Thermothelomyces thermophilus ATCC 42464",
    "Thermothielavioides terrestris NRRL 8126",
    "Fusarium oxysporum f. sp. lycopersici 4287",
    "Aspergillus nidulans FGSC A4",
    "Aspergillus fumigatus Af293",
    "Penicillium chrysogenum",
]

Animalia_Names_NCBI = [
    "Homo sapiens",
    "Pan troglodytes",
    "Gorilla gorilla gorilla",      #neu
    "Pongo abelii",         #neu
    "Macaca mulatta",       #neu
    "Microcebus murinus",   #neu
    "Microtus ochrogaster", #neu
    "Mus musculus",
    "Rattus norvegicus",
    "Oryctolagus cuniculus",
    "Ochotona princeps",    #neu
    "Canis lupus familiaris",
    "Felis catus",
    "Equus caballus",
    "Capra hircus",
    "Bos taurus",
    "Sus scrofa",
    "Monodelphis domestica",
    "Ornithorhynchus anatinus",
    "Gallus gallus",
    "Taeniopygia guttata",
    "Ficedula albicollis",
    "Strigops habroptila",
    "Falco rusticolus",
    "Aquila chrysaetos chrysaetos",
    "Calypte anna",
    "Chrysemys picta bellii",
    "Anolis carolinensis",
    "Lacerta agilis",
    "Xenopus tropicalis",
    "Rana temporaria",
    "Geotrypetes seraphini",
    "Takifugu rubripes",
    "Cynoglossus semilaevis",
    "Oreochromis niloticus",
    "Poecilia reticulata",
    "Danio rerio",
    "Salmo salar",
    "Lepisosteus oculatus",
    "Asterias rubens",
    "Ciona intestinalis",
    "Schistosoma mansoni",
    "Strongyloides ratti",
    "Caenorhabditis briggsae",
    "Caenorhabditis elegans",
    "Gigantopelta aegis",
    "Pomacea canaliculata",
    "Pecten maximus",
    "Crassostrea virginica",
    "Octopus sinensis",
    "Lepeophtheirus salmonis",
    "Penaeus monodon",
    "Rhipicephalus sanguineus",
    "Rhopalosiphum maidis",
    "Apis mellifera",
    "Bombus terrestris",
    "Nasonia vitripennis",
    "Anopheles gambiae str. PEST",
    "Drosophila pseudoobscura",
    "Drosophila melanogaster",
    "Drosophila simulans",
    "Aricia agestis",
]

Sorted_Names_All_NCBI = Animalia_Names_NCBI + Fungi_Names_NCBI + Protista_Names_NCBI + Embryophyta_Names_NCBI
Sorted_Names_All_NCBI_dicto = Animalia_Names_NCBI + ["Dictyostelium discoideum AX4",] + Fungi_Names_NCBI + Protista_Names_NCBI[1:] + Embryophyta_Names_NCBI

Embryophyta_Names_normal = [
    "Physcomitrium patens",
    "Brachypodium distachyon",
    "Oryza sativa",
    "Zea mays",
    "Sorghum bicolor",
    "Setaria italica",
    "Ananas comosus",
    "Elaeis guineensis",
    "Musa acuminata",
    "Asparagus officinalis",
    "Papaver somniferum",
    "Vitis vinifera",
    "Arabidopsis thaliana",
    "Brassica napus",
    "Camelina sativa",
    "Gossypium raimondii",
    "Theobroma cacao",
    "Citrus sinensis",
    "Populus trichocarpa",
    "Manihot esculenta",
    "Arachis duranensis",
    "Phaseolus vulgaris",
    "Cajanus cajan",
    "Vigna angularis",
    "Medicago truncatula",
    "Lupinus angustifolius",
    "Fragaria vesca",
    "Malus domestica",
    "Prunus mume",
    "Cucumis sativus",
    "Beta vulgaris",
    "Nicotiana attenuata",
    "Sesamum indicum",
    "Helianthus annuus",
]

Protista_Names_normal = [
    "Dictyostelium discoideum",
    "Leishmania donovani",
    "Leishmania infantum",
    "Leishmania major",
    "Trypanosoma brucei",
    "Neospora caninum",
    "Toxoplasma gondii",
    "Cryptosporidium parvum",
    "Plasmodium vivax",
    "Plasmodium falciparum ",
    "Plasmodium berghei",
    "Plasmodium cynomolgi",
    "Plasmodium coatneyi",
    "Plasmodium gaboni",
    "Theileria annulata",
    "Theileria parva",
    "Theileria orientalis",
    "Babesia microti",
    "Babesia bigemina",
    "Paramecium tetraurelia",
    "Phaeodactylum tricornutum",
    "Ectocarpus siliculosus",
    "Thalassiosira pseudonana",
    "Nannochloropsis gaditana",
    "Cyanidioschyzon merolae",
    "Chlamydomonas reinhardtii",
    "Micromonas commoda",
    "Bathycoccus prasinos",
    "Ostreococcus lucimarinus",
    "Ostreococcus tauri",
]

Fungi_Names_normal = [
    "Encephalitozoon cuniculi",
    "Encephalitozoon intestinalis",
    "Ustilago maydis",
    "Sporisorium reilianum",
    "Cryptococcus gattii",
    "Pyrrhoderma noxium",
    "Schizosaccharomyces pombe",
    "Saccharomyces cerevisiae",
    "Tetrapisispora phaffii",
    "Tetrapisispora blattae",
    "Zygosaccharomyces rouxii",
    "Naumovozyma castellii",
    "Lachancea thermotolerans",
    "Eremothecium gossypii",
    "Candida glabrata",
    "Candida albicans",
    "Debaryomyces hansenii",
    "Komagataella phaffii",
    "Yarrowia lipolytica",
    "Pichia kudriavzevii",
    "Ogataea parapolymorpha",
    "Zymoseptoria tritici",
    "Neurospora crassa",
    "Thermothelomyces thermophilus",
    "Thermothielavioides terrestris",
    "Fusarium oxysporum",
    "Aspergillus nidulans",
    "Aspergillus fumigatus",
    "Penicillium chrysogenum",
]

Animalia_Names_normal = [
    "Homo sapiens",
    "Pan troglodytes",
    "Gorilla gorilla",      #neu
    "Pongo abelii",         #neu
    "Macaca mulatta",       #neu
    "Microcebus murinus",   #neu
    "Microtus ochrogaster", #neu
    "Mus musculus",
    "Rattus norvegicus",
    "Oryctolagus cuniculus",
    "Ochotona princeps",    #neu
    "Canis lupus familiaris",
    "Felis catus",
    "Equus caballus",
    "Capra hircus",
    "Bos taurus",
    "Sus scrofa",
    "Monodelphis domestica",
    "Ornithorhynchus anatinus",
    "Gallus gallus",
    "Taeniopygia guttata",
    "Ficedula albicollis",
    "Strigops habroptila",
    "Falco rusticolus",
    "Aquila chrysaetos",
    "Calypte anna",
    "Chrysemys picta",
    "Anolis carolinensis",
    "Lacerta agilis",
    "Xenopus tropicalis",
    "Rana temporaria",
    "Geotrypetes seraphini",
    "Takifugu rubripes",
    "Cynoglossus semilaevis",
    "Oreochromis niloticus",
    "Poecilia reticulata",
    "Danio rerio",
    "Salmo salar",
    "Lepisosteus oculatus",
    "Asterias rubens",
    "Ciona intestinalis",
    "Schistosoma mansoni",
    "Strongyloides ratti",
    "Caenorhabditis briggsae",
    "Caenorhabditis elegans",
    "Gigantopelta aegis",
    "Pomacea canaliculata",
    "Pecten maximus",
    "Crassostrea virginica",
    "Octopus sinensis",
    "Lepeophtheirus salmonis",
    "Penaeus monodon",
    "Rhipicephalus sanguineus",
    "Rhopalosiphum maidis",
    "Apis mellifera",
    "Bombus terrestris",
    "Nasonia vitripennis",
    "Anopheles gambiae",
    "Drosophila pseudoobscura",
    "Drosophila melanogaster",
    "Drosophila simulans",
    "Aricia agestis",
]

Sorted_Names_All_normal = Animalia_Names_normal + Fungi_Names_normal + Protista_Names_normal + Embryophyta_Names_normal



Embryophyta_organism_class = {
    "Physcomitrium patens"                  :"Embryophyten",
    "Brachypodium distachyon"               :"Embryophyten",
    "Oryza sativa Japonica Group"           :"Embryophyten",
    "Zea mays"                              :"Embryophyten",
    "Sorghum bicolor"                       :"Embryophyten",
    "Setaria italica"                       :"Embryophyten",
    "Ananas comosus"                        :"Embryophyten",
    "Elaeis guineensis"                     :"Embryophyten",
    "Musa acuminata subsp. malaccensis"     :"Embryophyten",
    "Asparagus officinalis"                 :"Embryophyten",
    "Papaver somniferum"                    :"Embryophyten",
    "Vitis vinifera"                        :"Embryophyten",
    "Arabidopsis thaliana"                  :"Embryophyten",
    "Brassica napus"                        :"Embryophyten",
    "Camelina sativa"                       :"Embryophyten",
    "Gossypium raimondii"                   :"Embryophyten",
    "Theobroma cacao"                       :"Embryophyten",
    "Citrus sinensis"                       :"Embryophyten",
    "Populus trichocarpa"                   :"Embryophyten",
    "Manihot esculenta"                     :"Embryophyten",
    "Arachis duranensis"                    :"Embryophyten",
    "Phaseolus vulgaris"                    :"Embryophyten",
    "Cajanus cajan"                         :"Embryophyten",
    "Vigna angularis"                       :"Embryophyten",
    "Medicago truncatula"                   :"Embryophyten",
    "Lupinus angustifolius"                 :"Embryophyten",
    "Fragaria vesca subsp. vesca"           :"Embryophyten",
    "Malus domestica"                       :"Embryophyten",
    "Prunus mume"                           :"Embryophyten",
    "Cucumis sativus"                       :"Embryophyten",
    "Beta vulgaris subsp. vulgaris"         :"Embryophyten",
    "Nicotiana attenuata"                   :"Embryophyten",
    "Sesamum indicum"                       :"Embryophyten",
    "Helianthus annuus"                     :"Embryophyten",
}

Protista_organism_class = {
    "Dictyostelium discoideum AX4"              :"Amöben",
    "Leishmania donovani"                       :"Eukaryoten",
    "Leishmania infantum JPCM5"                 :"Eukaryoten",
    "Leishmania major strain Friedlin"          :"Eukaryoten",
    "Trypanosoma brucei brucei TREU927"         :"Eukaryoten",
    "Neospora caninum Liverpool"                :"Eukaryoten",
    "Toxoplasma gondii ME49"                    :"Eukaryoten",
    "Cryptosporidium parvum Iowa II"            :"Eukaryoten",
    "Plasmodium vivax"                          :"Eukaryoten",
    "Plasmodium falciparum 3D7"                 :"Eukaryoten",
    "Plasmodium berghei ANKA"                   :"Eukaryoten",
    "Plasmodium cynomolgi strain B"             :"Eukaryoten",
    "Plasmodium coatneyi"                       :"Eukaryoten",
    "Plasmodium gaboni"                         :"Eukaryoten",
    "Theileria annulata"                        :"Eukaryoten",
    "Theileria parva strain Muguga"             :"Eukaryoten",
    "Theileria orientalis strain Shintoku"      :"Eukaryoten",
    "Babesia microti strain RI"                 :"Eukaryoten",
    "Babesia bigemina"                          :"Eukaryoten",
    "Paramecium tetraurelia strain d4-2"        :"Eukaryoten",
    "Phaeodactylum tricornutum CCAP 1055_1"     :"Eukaryoten",
    "Ectocarpus siliculosus"                    :"Eukaryoten",
    "Thalassiosira pseudonana CCMP1335"         :"Eukaryoten",
    "Nannochloropsis gaditana"                  :"Eukaryoten",
    "Cyanidioschyzon merolae strain 10D"        :"Algen",
    "Chlamydomonas reinhardtii"                 :"Algen",
    "Micromonas commoda"                        :"Algen",
    "Bathycoccus prasinos"                      :"Algen",
    "Ostreococcus lucimarinus CCE9901"          :"Algen",
    "Ostreococcus tauri"                        :"Algen",
}

Protista_organism_classv2 = {
    "Dictyostelium discoideum AX4"              :"Amöben",
    "Leishmania donovani"                       :"Euglenozoa",
    "Leishmania infantum JPCM5"                 :"Euglenozoa",
    "Leishmania major strain Friedlin"          :"Euglenozoa",
    "Trypanosoma brucei brucei TREU927"         :"Euglenozoa",
    "Neospora caninum Liverpool"                :"Eukaryoten",
    "Toxoplasma gondii ME49"                    :"Eukaryoten",
    "Cryptosporidium parvum Iowa II"            :"Eukaryoten",
    "Plasmodium vivax"                          :"Eukaryoten",
    "Plasmodium falciparum 3D7"                 :"Eukaryoten",
    "Plasmodium berghei ANKA"                   :"Eukaryoten",
    "Plasmodium cynomolgi strain B"             :"Eukaryoten",
    "Plasmodium coatneyi"                       :"Eukaryoten",
    "Plasmodium gaboni"                         :"Eukaryoten",
    "Theileria annulata"                        :"Eukaryoten",
    "Theileria parva strain Muguga"             :"Eukaryoten",
    "Theileria orientalis strain Shintoku"      :"Eukaryoten",
    "Babesia microti strain RI"                 :"Eukaryoten",
    "Babesia bigemina"                          :"Eukaryoten",
    "Paramecium tetraurelia strain d4-2"        :"Eukaryoten",
    "Phaeodactylum tricornutum CCAP 1055_1"     :"Eukaryoten",
    "Ectocarpus siliculosus"                    :"Eukaryoten",
    "Thalassiosira pseudonana CCMP1335"         :"Eukaryoten",
    "Nannochloropsis gaditana"                  :"Eukaryoten",
    "Cyanidioschyzon merolae strain 10D"        :"Algen",
    "Chlamydomonas reinhardtii"                 :"Algen",
    "Micromonas commoda"                        :"Algen",
    "Bathycoccus prasinos"                      :"Algen",
    "Ostreococcus lucimarinus CCE9901"          :"Algen",
    "Ostreococcus tauri"                        :"Algen",
}

Fungi_organism_class = {
    "Encephalitozoon cuniculi GB-M1"                    :"unicellular Fungi",
    "Encephalitozoon intestinalis ATCC 50506"           :"unicellular Fungi",
    "Ustilago maydis 521"                               :"higher Fungi",
    "Sporisorium reilianum SRZ2"                        :"higher Fungi",
    "Cryptococcus gattii WM276"                         :"higher Fungi",
    "Pyrrhoderma noxium"                                :"higher Fungi",
    "Schizosaccharomyces pombe"                         :"higher Fungi",
    "Saccharomyces cerevisiae S288C"                    :"higher Fungi",
    "Tetrapisispora phaffii CBS 4417"                   :"higher Fungi",
    "Tetrapisispora blattae CBS 6284"                   :"higher Fungi",
    "Zygosaccharomyces rouxii"                          :"higher Fungi",
    "Naumovozyma castellii CBS 4309"                    :"higher Fungi",
    "Lachancea thermotolerans CBS 6340"                 :"higher Fungi",
    "Eremothecium gossypii ATCC 10895"                  :"higher Fungi",
    "[Candida] glabrata"                                :"higher Fungi",
    "Candida albicans SC5314"                           :"higher Fungi",
    "Debaryomyces hansenii CBS767"                      :"higher Fungi",
    "Komagataella phaffii GS115"                        :"higher Fungi",
    "Yarrowia lipolytica CLIB122"                       :"higher Fungi",
    "Pichia kudriavzevii"                               :"higher Fungi",
    "Ogataea parapolymorpha DL-1"                       :"higher Fungi",
    "Zymoseptoria tritici IPO323"                       :"higher Fungi",
    "Neurospora crassa OR74A"                           :"higher Fungi",
    "Thermothelomyces thermophilus ATCC 42464"          :"higher Fungi",
    "Thermothielavioides terrestris NRRL 8126"          :"higher Fungi",
    "Fusarium oxysporum f. sp. lycopersici 4287"        :"higher Fungi",
    "Aspergillus nidulans FGSC A4"                      :"higher Fungi",
    "Aspergillus fumigatus Af293"                       :"higher Fungi",
    "Penicillium chrysogenum"                           :"higher Fungi",
}

Animalia_organism_class = {
    "Homo sapiens"                          :"Mammalia",
    "Pan troglodytes"                       :"Mammalia",
    "Gorilla gorilla gorilla"               :"Mammalia",
    "Pongo abelii"                          :"Mammalia",
    "Macaca mulatta"                        :"Mammalia",
    "Microcebus murinus"                    :"Mammalia",
    "Microtus ochrogaster"                  :"Mammalia",
    "Mus musculus"                          :"Mammalia",
    "Rattus norvegicus"                     :"Mammalia",
    "Oryctolagus cuniculus"                 :"Mammalia",
    "Ochotona princeps"                     :"Mammalia",
    "Canis lupus familiaris"                :"Mammalia",
    "Felis catus"                           :"Mammalia",
    "Equus caballus"                        :"Mammalia",
    "Capra hircus"                          :"Mammalia",
    "Bos taurus"                            :"Mammalia",
    "Sus scrofa"                            :"Mammalia",
    "Monodelphis domestica"                 :"Mammalia",
    "Ornithorhynchus anatinus"              :"Mammalia",
    "Gallus gallus"                         :"Aves",
    "Taeniopygia guttata"                   :"Aves",
    "Ficedula albicollis"                   :"Aves",
    "Strigops habroptila"                   :"Aves",
    "Falco rusticolus"                      :"Aves",
    "Aquila chrysaetos chrysaetos"          :"Aves",
    "Calypte anna"                          :"Aves",
    "Chrysemys picta bellii"                :"Rep., Amphib. and Fish",
    "Anolis carolinensis"                   :"Rep., Amphib. and Fish",
    "Lacerta agilis"                        :"Rep., Amphib. and Fish",
    "Xenopus tropicalis"                    :"Rep., Amphib. and Fish",
    "Rana temporaria"                       :"Rep., Amphib. and Fish",
    "Geotrypetes seraphini"                 :"Rep., Amphib. and Fish",
    "Takifugu rubripes"                     :"Rep., Amphib. and Fish",
    "Cynoglossus semilaevis"                :"Rep., Amphib. and Fish",
    "Oreochromis niloticus"                 :"Rep., Amphib. and Fish",
    "Poecilia reticulata"                   :"Rep., Amphib. and Fish",
    "Danio rerio"                           :"Rep., Amphib. and Fish",
    "Salmo salar"                           :"Rep., Amphib. and Fish",
    "Lepisosteus oculatus"                  :"Rep., Amphib. and Fish",
    "Asterias rubens"                       :"Invertebrates",
    "Ciona intestinalis"                    :"Invertebrates",
    "Schistosoma mansoni"                   :"Invertebrates",
    "Strongyloides ratti"                   :"Invertebrates",
    "Caenorhabditis briggsae"               :"Invertebrates",
    "Caenorhabditis elegans"                :"Invertebrates",
    "Gigantopelta aegis"                    :"Invertebrates",
    "Pomacea canaliculata"                  :"Invertebrates",
    "Pecten maximus"                        :"Invertebrates",
    "Crassostrea virginica"                 :"Invertebrates",
    "Octopus sinensis"                      :"Invertebrates",
    "Lepeophtheirus salmonis"               :"Invertebrates",
    "Penaeus monodon"                       :"Invertebrates",
    "Rhipicephalus sanguineus"              :"Invertebrates",
    "Rhopalosiphum maidis"                  :"Insecta",
    "Apis mellifera"                        :"Insecta",
    "Bombus terrestris"                     :"Insecta",
    "Nasonia vitripennis"                   :"Insecta",
    "Anopheles gambiae str. PEST"           :"Insecta",
    "Drosophila pseudoobscura"              :"Insecta",
    "Drosophila melanogaster"               :"Insecta",
    "Drosophila simulans"                   :"Insecta",
    "Aricia agestis"                        :"Insecta",
}



"""
Embryophyta_organism_class = {
    "Physcomitrium patens"                  :"Moss",
    "Brachypodium distachyon"               :"Monocots",
    "Oryza sativa Japonica Group"           :"Monocots",
    "Zea mays"                              :"Monocots",
    "Sorghum bicolor"                       :"Monocots",
    "Setaria italica"                       :"Monocots",
    "Ananas comosus"                        :"Monocots",
    "Elaeis guineensis"                     :"Monocots",
    "Musa acuminata subsp. malaccensis"     :"Monocots",
    "Asparagus officinalis"                 :"Monocots",
    "Papaver somniferum"                    :"Eudicots",
    "Vitis vinifera"                        :"Eudicots",
    "Arabidopsis thaliana"                  :"Eudicots",
    "Brassica napus"                        :"Eudicots",
    "Camelina sativa"                       :"Eudicots",
    "Gossypium raimondii"                   :"Eudicots",
    "Theobroma cacao"                       :"Eudicots",
    "Citrus sinensis"                       :"Eudicots",
    "Populus trichocarpa"                   :"Eudicots",
    "Manihot esculenta"                     :"Eudicots",
    "Arachis duranensis"                    :"Eudicots",
    "Phaseolus vulgaris"                    :"Eudicots",
    "Cajanus cajan"                         :"Eudicots",
    "Vigna angularis"                       :"Eudicots",
    "Medicago truncatula"                   :"Eudicots",
    "Lupinus angustifolius"                 :"Eudicots",
    "Fragaria vesca subsp. vesca"           :"Eudicots",
    "Malus domestica"                       :"Eudicots",
    "Prunus mume"                           :"Eudicots",
    "Cucumis sativus"                       :"Eudicots",
    "Beta vulgaris subsp. vulgaris"         :"Eudicots",
    "Nicotiana attenuata"                   :"Eudicots",
    "Sesamum indicum"                       :"Eudicots",
    "Helianthus annuus"                     :"Eudicots",
}
"""
Protista_organism_class = {
    "Dictyostelium discoideum AX4"              :"Amoeba",
    "Leishmania donovani"                       :"Euglenozoa",
    "Leishmania infantum JPCM5"                 :"Euglenozoa",
    "Leishmania major strain Friedlin"          :"Euglenozoa",
    "Trypanosoma brucei brucei TREU927"         :"Euglenozoa",
    "Neospora caninum Liverpool"                :"Protists",
    "Toxoplasma gondii ME49"                    :"Protists",
    "Cryptosporidium parvum Iowa II"            :"Protists",
    "Plasmodium vivax"                          :"Protists",
    "Plasmodium falciparum 3D7"                 :"Protists",
    "Plasmodium berghei ANKA"                   :"Protists",
    "Plasmodium cynomolgi strain B"             :"Protists",
    "Plasmodium coatneyi"                       :"Protists",
    "Plasmodium gaboni"                         :"Protists",
    "Theileria annulata"                        :"Protists",
    "Theileria parva strain Muguga"             :"Protists",
    "Theileria orientalis strain Shintoku"      :"Protists",
    "Babesia microti strain RI"                 :"Protists",
    "Babesia bigemina"                          :"Protists",
    "Paramecium tetraurelia strain d4-2"        :"Protists",
    "Phaeodactylum tricornutum CCAP 1055_1"     :"Protists",
    "Ectocarpus siliculosus"                    :"Protists",
    "Thalassiosira pseudonana CCMP1335"         :"Protists",
    "Nannochloropsis gaditana"                  :"Protists",
    "Cyanidioschyzon merolae strain 10D"        :"Algae",
    "Chlamydomonas reinhardtii"                 :"Algae",
    "Micromonas commoda"                        :"Algae",
    "Bathycoccus prasinos"                      :"Algae",
    "Ostreococcus lucimarinus CCE9901"          :"Algae",
    "Ostreococcus tauri"                        :"Algae",
}


Fungi_organism_class = {
    "Encephalitozoon cuniculi GB-M1"                    :"unicellular Fungi",
    "Encephalitozoon intestinalis ATCC 50506"           :"unicellular Fungi",
    "Ustilago maydis 521"                               :"higher Fungi",
    "Sporisorium reilianum SRZ2"                        :"higher Fungi",
    "Cryptococcus gattii WM276"                         :"higher Fungi",
    "Pyrrhoderma noxium"                                :"higher Fungi",
    "Schizosaccharomyces pombe"                         :"higher Fungi",
    "Saccharomyces cerevisiae S288C"                    :"higher Fungi",
    "Tetrapisispora phaffii CBS 4417"                   :"higher Fungi",
    "Tetrapisispora blattae CBS 6284"                   :"higher Fungi",
    "Zygosaccharomyces rouxii"                          :"higher Fungi",
    "Naumovozyma castellii CBS 4309"                    :"higher Fungi",
    "Lachancea thermotolerans CBS 6340"                 :"higher Fungi",
    "Eremothecium gossypii ATCC 10895"                  :"higher Fungi",
    "[Candida] glabrata"                                :"higher Fungi",
    "Candida albicans SC5314"                           :"higher Fungi",
    "Debaryomyces hansenii CBS767"                      :"higher Fungi",
    "Komagataella phaffii GS115"                        :"higher Fungi",
    "Yarrowia lipolytica CLIB122"                       :"higher Fungi",
    "Pichia kudriavzevii"                               :"higher Fungi",
    "Ogataea parapolymorpha DL-1"                       :"higher Fungi",
    "Zymoseptoria tritici IPO323"                       :"higher Fungi",
    "Neurospora crassa OR74A"                           :"higher Fungi",
    "Thermothelomyces thermophilus ATCC 42464"          :"higher Fungi",
    "Thermothielavioides terrestris NRRL 8126"          :"higher Fungi",
    "Fusarium oxysporum f. sp. lycopersici 4287"        :"higher Fungi",
    "Aspergillus nidulans FGSC A4"                      :"higher Fungi",
    "Aspergillus fumigatus Af293"                       :"higher Fungi",
    "Penicillium chrysogenum"                           :"higher Fungi",
}

Animalia_organism_class = {
    "Pan troglodytes"                       :"Mammalia",
    "Homo sapiens"                          :"Mammalia",
    "Gorilla gorilla gorilla"               :"Mammalia",
    "Pongo abelii"                          :"Mammalia",
    "Macaca mulatta"                        :"Mammalia",
    "Microcebus murinus"                    :"Mammalia",
    "Microtus ochrogaster"                  :"Mammalia",
    "Mus musculus"                          :"Mammalia",
    "Rattus norvegicus"                     :"Mammalia",
    "Ochotona princeps"                     :"Mammalia",
    "Oryctolagus cuniculus"                 :"Mammalia",
    "Canis lupus familiaris"                :"Mammalia",
    "Felis catus"                           :"Mammalia",
    "Equus caballus"                        :"Mammalia",
    "Capra hircus"                          :"Mammalia",
    "Bos taurus"                            :"Mammalia",
    "Sus scrofa"                            :"Mammalia",
    "Monodelphis domestica"                 :"Mammalia",
    "Ornithorhynchus anatinus"              :"Mammalia",
    "Gallus gallus"                         :"Aves",
    "Taeniopygia guttata"                   :"Aves",
    "Ficedula albicollis"                   :"Aves",
    "Strigops habroptila"                   :"Aves",
    "Falco rusticolus"                      :"Aves",
    "Aquila chrysaetos chrysaetos"          :"Aves",
    "Calypte anna"                          :"Aves",
    "Chrysemys picta bellii"                :"Rep., etc.",
    "Anolis carolinensis"                   :"Rep., etc.",
    "Lacerta agilis"                        :"Rep., etc.",
    "Xenopus tropicalis"                    :"Rep., etc.",
    "Rana temporaria"                       :"Rep., etc.",
    "Geotrypetes seraphini"                 :"Rep., etc.",
    "Takifugu rubripes"                     :"Rep., etc.",
    "Cynoglossus semilaevis"                :"Rep., etc.",
    "Oreochromis niloticus"                 :"Rep., etc.",
    "Poecilia reticulata"                   :"Rep., etc.",
    "Danio rerio"                           :"Rep., etc.",
    "Salmo salar"                           :"Rep., etc.",
    "Lepisosteus oculatus"                  :"Rep., etc.",
    "Asterias rubens"                       :"Invert.",
    "Ciona intestinalis"                    :"Invert.",
    "Schistosoma mansoni"                   :"Invert.",
    "Strongyloides ratti"                   :"Invert.",
    "Caenorhabditis briggsae"               :"Invert.",
    "Caenorhabditis elegans"                :"Invert.",
    "Gigantopelta aegis"                    :"Invert.",
    "Pomacea canaliculata"                  :"Invert.",
    "Pecten maximus"                        :"Invert.",
    "Crassostrea virginica"                 :"Invert.",
    "Octopus sinensis"                      :"Invert.",
    "Lepeophtheirus salmonis"               :"Invert.",
    "Penaeus monodon"                       :"Invert.",
    "Rhipicephalus sanguineus"              :"Invert.",
    "Rhopalosiphum maidis"                  :"Insecta",
    "Apis mellifera"                        :"Insecta",
    "Bombus terrestris"                     :"Insecta",
    "Nasonia vitripennis"                   :"Insecta",
    "Anopheles gambiae str. PEST"           :"Insecta",
    "Drosophila pseudoobscura"              :"Insecta",
    "Drosophila melanogaster"               :"Insecta",
    "Drosophila simulans"                   :"Insecta",
    "Aricia agestis"                        :"Insecta",
}

Nucleomorph_organism_class = {
    "Bigelowiella natans"                   :"Nucleomorph",
    "Guillardia theta"                      :"Nucleomorph",
    "Hemiselmis andersenii"                 :"Nucleomorph",
    "Cryptomonas paramecium"                :"Nucleomorph",
    "Chroomonas mesostigmatica CCMP1168"    :"Nucleomorph",
    "Chroomonas mesostigmatica"             :"Nucleomorph",
}


all_orga_classes = {}
for dict in Embryophyta_organism_class,Protista_organism_class,Fungi_organism_class,Animalia_organism_class,Nucleomorph_organism_class:
    all_orga_classes.update(dict)

def name_to_class(name):
    if name in all_orga_classes.keys():
        return all_orga_classes[name]
    elif name in orga_name_NCBI_dict.keys():
        new_name = orga_name_NCBI_dict[name]
        if new_name in all_orga_classes.keys():
            return all_orga_classes[new_name]
    else:
        print (name)
        print ("!!!Error class of "+name+" not found!!!")
        return None